myschoolcommute/urls.py
from django.conf.urls import url, include, patterns
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()


urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include("massadmin.urls")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Translation app
    url(r'^rosetta/', include('rosetta.urls')),

    #Accounts
    url(r'^accounts/', include('accounts.urls')),

    # district/school list on front-page
    url(r'^$', 'survey.views.index', name='home'),

    # static pages
    url(r'^about/$', TemplateView.as_view(template_name='survey/about.html'), name='about'),
    url(r'^resources/$', TemplateView.as_view(template_name='survey/resources.html'), name='resources'),

    # custom admin pages
    url(r'^districts/$', 'survey.views.district_list', name='district_list'),
    url(r'^(?P<district_slug>[-\w]+)/(?P<school_slug>[-\w]+)/edit/$', 'survey.views.school_edit', name='school_edit'),
    url(r'^(?P<district_slug>[-\w]+)/(?P<school_slug>[-\w]+)/batch/$', 'survey.views.batch_form', name='survey_batch_form'),

    # district
    url(r'^(?P<district_slug>[-\w]+)/$', 'survey.views.district', name='school_list'),
    url(r'^(?P<districtid>[-\w]+)/schools/$', 'survey.views.get_schools', name='disctrict_get_schools'),
    url(r'^(?P<districtid>[-\w]+)/streets/$', 'survey.views.get_streets', name='disctrict_get_streets'),

    # school
    url(r'^(?P<district_slug>[-\w]+)/(?P<school_slug>[-\w]+)/$', 'survey.views.form', name='survey_school_form'),
)

urlpatterns += patterns('',
    # Testing
    url(r'^testr/$', 'survey.views.testr'),

    # Generate report
    url(r'^(?P<school_id>\d+)/(?P<start>\d{4}-\d{2}-\d{2})_(?P<end>\d{4}-\d{2}-\d{2})_report\.pdf$', 'survey.views.school_report', name='school_report'),

    #Typeahead
    url(r'^(?P<school_id>\d+)/streets/(?P<query>[^/]*)/?$', 'survey.views.school_streets'),
    url(r'^(?P<school_id>\d+)/crossing/(?P<street>[^/]+)/(?P<query>[^/]*)/?$', 'survey.views.school_crossing' ),
    url(r'^(?P<school_id>\d+)/intersection/(?P<street1>[^/]+)/(?P<street2>[^/]*)/?$', 'survey.views.intersection' ),

    # admin data
    url(r'^(?P<school_id>\d+)/walkshed.geojson$', 'survey.maps.school_sheds_json', name='sheds_json'),
    url(r'^(?P<school_id>\d+)/surveys.geojson$', 'survey.maps.school_surveys_json', name='surveys_json'),
    url(r'^(?P<school_id>\d+)/walkshed.png$', 'survey.maps.school_sheds', name='school_sheds'),
    url(r'^(?P<school_id>\d+)/walkshed.(?P<format>\w+)$', 'survey.maps.school_sheds', name='school_sheds_format'),
    url(r'^survey_child_survey\.csv$', 'survey.views.surveys_csv', name='surveys_csv'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^walkboston/', include('walkboston.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    # Translation app
    (r'^rosetta/', include('rosetta.urls')),
    
    # district/school list on front-page
    (r'^$', 'survey.views.index'),
    
    # static pages
    (r'^about/$', direct_to_template, {'template': 'survey/about.html'}),
    
    # district
    (r'^(?P<district_slug>[-\w]+)/$', 'survey.views.district'),
    url(r'^(?P<districtid>[-\w]+)/schools/$', 'survey.views.get_schools', name='disctrict_get_schools'),
    url(r'^(?P<districtid>[-\w]+)/streets/$', 'survey.views.get_streets', name='disctrict_get_streets'),
    # school
    url(r'^(?P<district_slug>[-\w]+)/(?P<school_slug>[-\w]+)/$', 'survey.views.form', name='survey_school_form'),    
)

survey/models.py
from django.contrib.gis.db import models
from django.db.models import permalink
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.gis.geos import GEOSGeometry, MultiPolygon, Polygon, GeometryCollection
from django.core.urlresolvers import reverse

# lazy translation
from django.utils.translation import ugettext_lazy as _

# south introspection rules
try:
    from south.modelsinspector import add_introspection_rules
    add_introspection_rules([], ['^django\.contrib\.gis\.db\.models\.fields\.PointField'])
    add_introspection_rules([], ['^django\.contrib\.gis\.db\.models\.fields\.MultiPolygonField'])
    add_introspection_rules([], ['^django\.contrib\.gis\.db\.models\.fields\.MultiLineStringField'])
except ImportError:
    pass

from datetime import datetime, timedelta


class District(models.Model):
    """ School Districts """
    districtid = models.IntegerField(primary_key=True)
    distname = models.CharField(max_length=35)
    slug = models.SlugField(max_length=35, unique=True)
    startgrade = models.CharField(max_length=2)
    endgrade = models.CharField(max_length=2)
    distcode4 = models.CharField(max_length=4)
    distcode8 = models.CharField(max_length=8)

    geometry = models.MultiPolygonField(srid=26986)
    objects = models.GeoManager()

    @property
    def name(self):
        return self.distname

    def __unicode__(self):
        return self.distname

    class Meta:
        ordering = ['distname']


class CustomManager(models.GeoManager):
    def get_query_set(self):
        qs = super(CustomManager, self).get_query_set()
        return qs.defer('shed_05', 'shed_10', 'shed_15', 'shed_20', 'geometry')


class School(models.Model):
    """ School """
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True, null=True)

    schid = models.CharField('School ID', max_length=8, blank=True, null=True, unique=True)
    address = models.CharField(max_length=150, blank=True, null=True)
    town_mail = models.CharField(max_length=25, blank=True, null=True)
    town = models.CharField(max_length=25, blank=True, null=True)
    state = models.CharField(max_length=2, blank=True, null=True)
    zip = models.CharField(max_length=10, blank=True, null=True)
    principal = models.CharField(max_length=50, blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    fax = models.CharField(max_length=15, blank=True, null=True)
    grades = models.CharField(max_length=70, blank=True, null=True)
    schl_type = models.CharField(max_length=3, blank=True, null=True)
    districtid = models.ForeignKey('District', blank=True, null=True)

    survey_incentive = models.TextField(blank=True, null=True)
    # Renamed to disable for now
    _active = models.BooleanField(
        'Is survey active? (Disabled)', db_column='survey_active', default=False
    )

    # GeoDjango
    geometry = models.PointField(srid=26986)
    shed_05 = models.MultiPolygonField(srid=26986, null=True, blank=True)
    shed_10 = models.MultiPolygonField(srid=26986, null=True, blank=True)
    shed_15 = models.MultiPolygonField(srid=26986, null=True, blank=True)
    shed_20 = models.MultiPolygonField(srid=26986, null=True, blank=True)
    objects = CustomManager()


    def __init__(self, *args, **kwargs):
        super(School, self).__init__(*args, **kwargs)
        self.__init__geometry = self.geometry

    def __unicode__(self):
        return self.name

    @property
    def survey_active(self):
        return SurveySet.objects.filter(
            Q(school=self) &
            Q(begin__lte=datetime.now()) &
            Q(end__gte=datetime.now())
        ).count() > 0

    @property
    def district(self):
        return self.districtid

    @permalink
    def get_absolute_url(self):
        return ('survey_school_form', None, {'school_slug': self.slug, 'district_slug': self.districtid.slug})

    def get_intersections(self):
        # school_circle = self.geometry.buffer(5000)
        # intersections = Intersection.objects.filter(geometry__intersects=school_circle)
        relation = SchoolTown.objects.get(schid=self.schid)
        intersections = Intersection.objects.filter(town_id=relation.town_id)
        return intersections

    def update_sheds(self):
        from maps import get_sheds
        sheds = get_sheds(self.id)

        shed_05 = GEOSGeometry(sheds[0.5])
        shed_10 = GEOSGeometry(sheds[1.0])
        shed_15 = GEOSGeometry(sheds[1.5])
        shed_20 = GEOSGeometry(sheds[2.0])

        def coerce_to_multipolygon(geometry):
            if geometry.area == 0:
                return None

            if type(geometry) == MultiPolygon:
                return geometry
            elif type(geometry) == Polygon:
                return MultiPolygon(geometry)
            elif type(geometry) == GeometryCollection:
                polys = []
                for g in geometry:
                    if type(g) == Polygon:
                        polys.append(g)
                    elif type(g) == MultiPolygon:
                        polys += list(g)
                if any(polys):
                    return MultiPolygon(polys)
                else:
                    return None
            else:
                return geometry

        shed_20_ring = shed_20.difference(shed_15)
        self.shed_20 = coerce_to_multipolygon(shed_20_ring)

        shed_15_ring = shed_15.difference(shed_10)
        self.shed_15 = coerce_to_multipolygon(shed_15_ring)

        shed_10_ring = shed_10.difference(shed_05)
        self.shed_10 = coerce_to_multipolygon(shed_10_ring)

        self.shed_05 = coerce_to_multipolygon(shed_05)

    def save(self, *args, **kwargs):
        super(School, self).save(*args, **kwargs)

        SchoolTown.objects.create(schid=self.schid, name=self.name, town_id=self.districtid.districtid)

        # the geometry actually needs to be commited first to be used in update
        if 'commit' not in kwargs or kwargs['commit'] is not False:

            # new school
            if self.__init__geometry is None and self.geometry is not None:
                # new school, generate sheds
                self.update_sheds()
                # save the sheds
                super(School, self).save(*args, **kwargs)

            # school has moved
            elif not self.__init__geometry.equals_exact(self.geometry, 0.001):
                self.update_sheds()
                # save the sheds
                super(School, self).save(*args, **kwargs)

    class Meta:
        ordering = ['name']


class SchoolTown(models.Model):
    ogc_fid = models.AutoField(primary_key=True)
    schid = models.CharField(max_length=8, blank=True, null=True, unique=True)
    name = models.CharField(max_length=200)
    town_id = models.IntegerField(db_column='muni_id')

    class Meta:
        db_table = 'school_muni'


class Street(models.Model):
    """
    Streets to be returned as type-ahead in street-fields
    to limit the variety of street names and make geocoding
    more accurate.
    """
    name = models.CharField(max_length=240)
    districtid = models.ForeignKey('District', blank=True, null=True)

    geometry = models.MultiLineStringField(srid=26986)
    objects = models.GeoManager()

    def __unicode__(self):
        return self.name


class Intersection(models.Model):
    ogc_fid = models.IntegerField(primary_key=True)
    geometry = models.GeometryField(null=True, blank=True, srid=26986)
    st_name_1 = models.CharField(max_length=50, blank=True)
    st_name_2 = models.CharField(max_length=50, blank=True)
    town = models.CharField(max_length=50, blank=True)
    town_id = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True, db_column='long')

    objects = models.GeoManager()

    class Meta:
        db_table = 'survey_intersection'

    def __unicode__(self):
        return "%s - %s" % (self.st_name_1, self.st_name_2, )


class Survey(models.Model):
    """
    Survey base questions.
    """
    school = models.ForeignKey(School)
    street = models.CharField(max_length=50, blank=True, null=True)
    cross_st = models.CharField(
        'Cross street', max_length=50, blank=True, null=True
    )
    nr_vehicles = models.IntegerField(
        'Number of Vehicles', blank=True, null=True
    )
    nr_licenses = models.IntegerField(
        'Number of License', blank=True, null=True
    )
    ip = models.IPAddressField('IP Address', blank=True, null=True)
    # Mile, shortest driving distance, not walk/bike distance
    distance = models.FloatField(null=True)
    created = models.DateTimeField(null=True)
    modified = models.DateTimeField(auto_now=True, null=True)

    user = models.ForeignKey(User, null=True)
    # GeoDjango
    location = models.PointField(
        geography=True, blank=True, null=True, default='POINT(0 0)'
    )
    # default SRS 4326
    objects = models.GeoManager()

    def __unicode__(self):
        return u'%s' % (self.id)

    def update_location(self):
        if len(self.street) > 0 and len(self.cross_st) > 0:
            school_cross = self.school.get_intersections()
            crosses = school_cross.filter(
                Q(
                    Q(st_name_1__iexact=self.street) &
                    Q(st_name_2__iexact=self.cross_st)
                ) |
                Q(
                    Q(st_name_2__iexact=self.street) &
                    Q(st_name_1__iexact=self.cross_st)
                )
            )
            crosses = list(crosses)
            if len(crosses):
                self.location = crosses[0].geometry
                self.location.transform(4326)
            else:
                print 'No Intersection'

    def update_distance(self):
        from maps import get_driving_distance

        try:
            self.distance = get_driving_distance(

templates/survey/form.html
{% extends "base.html" %}
{% load i18n %}
{% load dbgettext_tags %}

{% block style %}

	select, input {
		margin-left: 10px;
		margin-right: 10px;
	}
	#button_addchild {
		margin-bottom: 18px;
	}
	#map_canvas {
		width: 100%; 
		height: 400px;
	}
	#map_legend {
		text-align: right;
	}
	#map_legend img {
		height: 16px;
	}

{% endblock %}

{% block javascript %}
<script src="http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.5.2.min.js" type="text/javascript"></script>
<script src="{{ MEDIA_URL }}js/jquery.shuffle.js" type="text/javascript"></script>
<script src="{{ MEDIA_URL }}js/jquery.cookie.js" type="text/javascript"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&language={{ LANGUAGE_CODE }}"></script> 
<script type="text/javascript">

$(document).ready(function() {
	
	// check if cookies are enabled
	$.cookie('test_cookie', 'testing', { path: '/' });
	if ($.cookie('test_cookie') !== 'testing') {
		alert("Please allow cookies for this site in your browser, otherwise the survey form might not work. Thank you!");
	}

{% if school %}

	// setting marker location
	var school = new google.maps.LatLng({{ school.location.y }}, {{ school.location.x }});
	
	// parsing hidden home location field
	var homeCoord = $("#id_location")
	.val()
	.substr(7, ($("#id_location").val().length - 8))
	.split(" ");
	
	// if we have a home location, render it
	if (parseFloat(homeCoord[0]) === 0) {
		var home = new google.maps.LatLng({{ school.location.y }}+0.002, {{ school.location.x }}-0.002);
	} else {
		var home = new google.maps.LatLng(homeCoord[1], homeCoord[0]);
	}
	// setting school id
	$("#id_school").val({{ school.id }});
	
{% else %}

	var school = new google.maps.LatLng(42.34, -71.0);
	var home = new google.maps.LatLng(42.335, -70.995);
	
{% endif %}
	
	var mapOptions = {
		zoom: 14,
		mapTypeId: google.maps.MapTypeId.ROADMAP,
		center: school
	};
 
	var map = new google.maps.Map(document.getElementById("map_canvas"),
		mapOptions);
    
    var iconSchool = "{{ MEDIA_URL }}img/school.png";
	var markerSchool = new google.maps.Marker({
		map:map,
		title:"{{ school.name }}",
		position: school,
		icon: iconSchool
	});
	var iconHome = "{{ MEDIA_URL }}img/home.png";
	var markerHome = new google.maps.Marker({
		map:map,
		title:"Please drag & drop the marker to the intersection closest to your home",
		draggable:true,
		animation: google.maps.Animation.DROP,
		position: home,
		icon: iconHome
	});
	// animation
	google.maps.event.addListener(markerHome, 'click', toggleBounce);
	// track marker dragging		
	google.maps.event.addListener(markerHome, 'dragend', function() {
		// write loc coord to hidden geometry field (in WGS84)
		$("#id_location").val("POINT (" + markerHome.position.lng() + " " +  markerHome.position.lat() + ")");
		// validate location
		validation["marker"] = true;
	});
	
	function toggleBounce() {
		if (markerH.getAnimation() != null) {
			markerH.setAnimation(null);
		} else {
			markerH.setAnimation(google.maps.Animation.BOUNCE);
		}
	}
	
	/***********************
	 *  children formsets  *
	 ***********************/
	
	var nrChildForms = $("#id_child_set-TOTAL_FORMS").val() - 1;
	
	// child-form counter
	// FIXME: count childforms, otherwise errorform breaks
	var childCount = 0;
	
	// form validation: min information is location and child mode
	var validation = {
		"formerror":{% if formerror %} true {% else %} false {% endif %},
		"marker": false // location not set
	};
	
	$("#surveyform").submit(function() {
		// check location field
		if ($("#id_location").val() === "POINT (0.0000000000000000 0.0000000000000000)") {
			validation.marker = false;
		} else {
			// required for django validation error page-reload
			validation.marker = true;
		}
		
      	// no location provided, harder to check with django form validation
		if (validation.marker === false && ($("#id_street").val() === "" || $("#id_cross_st").val() === "")) {
			alert("Please provide your street information.");
	      	return false;
		}
   });
		
	// dropoff detail functionality
	$.fn.dropoffDetails = function(child) {
		// reset and hide id_child_set-0-dropoff_to|_from fieldset
    	$("#id_child_set-" + child + "-dropoff, #id_child_set-" + child + "-pickup")
    	.each(function(index) {
    		$(this).parentsUntil("#id_child_set-" + child).hide();
    	});
		// bind change event to travelmode fields
		$(this).change(function() {
			// check for direction if child pickup or dropoff
    		direction = ($(this).attr("id").indexOf("from_school") >= 0) ? "pickup" : "dropoff";
			// check if selected value is in list of modes
			if ( $.inArray($(this).val(), ["fv", "cp"]) >= 0 ) { // show additional question
				$("#id_child_set-" + child + "-" + direction).parentsUntil("#id_child_set-" + child).show(500);				
			} else { // hide and clear value
				$("#id_child_set-" + child + "-" + direction).parentsUntil("#id_child_set-" + child).hide(500);
				$("#id_child_set-" + child + "-" + direction).val("");
			}
		});
	}
	
	// FIXME: create a function for checking dropoff/pickup options
	
	// add another child
	$("#button_addchild").click(function() {
		
		// clone last child-form
		var $childformClone = $("#id_child_set-" + childCount).clone();
		
		// update form attributes in clone to new child
    	$childformClone
		.attr("id", "id_child_set-" + (childCount+1))
		.find("input,select,label")
		.each(function(index) {
			if ($(this).is("select") || $(this).is("input")) {
				newId = $(this).attr("id").replace("id_child_set-" + childCount,"id_child_set-" + (childCount+1));
				newName = $(this).attr("name").replace("child_set-" + childCount,"child_set-" + (childCount+1));
				$(this)
				.attr("id", newId)
				.attr("name", newName);    				
			}
			if ($(this).is("label")) {
				newAttr = $(this).attr("for").replace("id_child_set-" + childCount,"id_child_set-" + (childCount+1));
				$(this).attr("for", newAttr);
			}
		});
		
		// append clone to page
		$childformClone.appendTo("#children").slideDown(500);
		
		$('html, body').animate({
			scrollTop: $("#button_submit").offset().top 
		}, 1000);
		// bind dropoffDetail function to cloned form
		$("#id_child_set-" + (childCount+1) + "-from_school, #id_child_set-" + (childCount+1) + "-to_school").dropoffDetails(childCount+1);
		// increase counter
		childCount++;
		// update management form number (form-id count starts at, real number at 1, that's why it must be +1)
		$("#id_child_set-TOTAL_FORMS").val(childCount+1);
		// don't submit form
		return false;
	});	
	
	// catch django form validation error page-reload
	// bind dropoffDetail function to start form
    if (!validation.formerror) $("#id_child_set-0-from_school, #id_child_set-0-to_school").dropoffDetails(0);
    
    // random order of modes
    $("#id_child_set-0-to_school, #id_child_set-0-from_school").shuffle();
    
});

</script>

{% endblock %}

{% block body %}

{% if school %}

<div class="prepend-2 span-20 append-2 last {{ LANGUAGE_CODE }}">
	
	<h1>{{ school.name }}</h1>
	
	<h2>
		{% blocktrans %}
		Important School Travel Survey
		{% endblocktrans %}
	</h2>
	
	<p><strong>
		{% blocktrans %}
		Dear Parent or Guardian,
		{% endblocktrans %}
	</strong></p>
 
	<p>
		{% blocktrans with school.name as schoolname %}
		{{ schoolname }} would like to learn how students get to and from school. 
		This information will be used to plan safe and healthy walking options for students.
		{% endblocktrans %}
	</p>
		
	<p><em>
		{% blocktrans %}
		This survey will take less than 3 minutes to complete.
		{% endblocktrans %}
	</em></p>
	
	<p>
		{% blocktrans %}
		Please complete one survey for each child at this school by <strong>Friday, May 27</strong>.
		{% endblocktrans %}
	</p>

	<p><strong>
		{% blocktrans %}
		Your school earns money when you complete this survey!
		{% endblocktrans %}
	</strong><br>	
		{% trans school.survey_incentive %}
	</p>
		
	<p><strong>
		{% blocktrans %}
		Please do not complete the online survey if you have already submitted a paper copy.
		{% endblocktrans %}
		</strong>
	</p>
	
	 
	
	<form id="surveyform" action="." method="POST">
		
		{% csrf_token %}
		
		{{ surveyformset.management_form }}
		
		<fieldset class="module aligned">
			
			<p class="large">
				{% blocktrans %}
				What street do you live on?
				{% endblocktrans %}
			</p>
	
			<p>
				{% blocktrans %}								
				Please drag and drop the yellow home-marker to an intersection on your street, near your home:
				{% endblocktrans %}
				
			</p>
			
			<div id="map_canvas">map div</div>
			<div id="map_legend" class="small"><img src="{{ MEDIA_URL }}img/home.png" height="20" alt="Home marker" > ... {% blocktrans %}your home{% endblocktrans %} <img src="{{ MEDIA_URL }}img/school.png" height="20" alt="Home marker" > ... {{ school.name }}</div>
			
			<p>
				{% blocktrans %}
				...or tell us the street intersection closest to your home.
				{% endblocktrans %}
			</p>
			
			<div class="form-row">
				
					{{ surveyform.street.errors }}
					{% trans surveyform.street.label %}: {{ surveyform.street }}<br>
					{{ surveyform.cross_st.errors }}
					{% trans surveyform.cross_st.label %}: {{ surveyform.cross_st }}
			
			</div>
			
			{{ surveyform.location }}
			
		</fieldset>
		
		<div id="children">
		
			{% for form in surveyformset.forms %}
		
			<fieldset id="id_child_set-0" class="module aligned">
			
			{% for field in form %}
			
				{% if not field.is_hidden %}
				<div class="form-row">
					<div class="field-box">											
						
						{% if field.errors %}
								<div class="error">
							{% for error in field.errors %}
							    	{{ error|escape }}<br>
							{% endfor %}
									<span class="large">{{ field.label }}</span> {{ field }}
								</div>
						{% else %}
							<span class="large">{{ field.label }}</span> {{ field }}
						{% endif %}
					</div>
				</div>
				{% else %}
					{{ field }}
				{% endif %}
			{% endfor %}
			
			</fieldset>
		
			{% endfor %}
		
		</div>
		
		<button id="button_addchild">
			{% blocktrans %}
			Add another child at this school
			{% endblocktrans %}
		</button>
		
		<fieldset class="module aligned">
		
			<div class="form-row">
				<div class="field-box">
					
					{% if surveyform.nr_vehicles.errors %}
						<div class="error">
						{% for error in surveyform.nr_vehicles.errors %}
						    {{ error|escape }}<br>
						{% endfor %}
							<span class="large">{% trans surveyform.nr_vehicles.label %}</span> {{ surveyform.nr_vehicles }}
						</div>
					{% else %}
						<span class="large">{% trans surveyform.nr_vehicles.label %}</span> {{ surveyform.nr_vehicles }}
					{% endif %}
					
				</div>
			</div>
			
			<div class="form-row">
				<div class="field-box">
					
					{% if surveyform.nr_licenses.errors %}
						<div class="error">
						{% for error in surveyform.nr_licenses.errors %}
						    {{ error|escape }}<br>
						{% endfor %}
							<span class="large">{% trans surveyform.nr_licenses.label %}</span> {{ surveyform.nr_licenses }}
						</div>
					{% else %}
						<span class="large">{% trans surveyform.nr_licenses.label %}</span> {{ surveyform.nr_licenses }}
					{% endif %}
					
				</div>
			</div>
		
		</fieldset>
		
		<button id="button_submit" type="submit">
			{% blocktrans %}
			Submit Survey
			{% endblocktrans %}
		</button>
	
	</form>
		
</div>

{% endif %}

{% endblock %}

templates/survey/index.html
{% extends "base.html" %}
{% load i18n %}

{% block javascript %}
	<script src="http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.5.2.min.js" type="text/javascript"></script>
	<script src="{{ MEDIA_URL }}js/jquery.easing.js" type="text/javascript"></script>
	<script src="{{ MEDIA_URL }}js/jquery.collapse.js" type="text/javascript"></script>
	<script type="text/javascript">
		$(function(){
			$('#collapser').jqcollapse({
				slide: true,
				speed: 300,
				easing: 'easeOutCubic'
			});
		});
	</script>
{% endblock %}

{% block body %}

<div class="prepend-2 span-20 append-2 last {{ LANGUAGE_CODE }}">
	
	<h1>
		{% blocktrans %}
		Available districts and schools:
		{% endblocktrans %}
	</h1>
	
	<ul id="collapser">
	
	{% for district in districts %}
	
		<li><span class="large loud">{{ district.name }}</span>
			<ul>
			{% for school in district.school_set.select_related %}
			
				<li><a href="{{ district.slug }}/{{ school.slug }}">{{ school.name }}</a></li>
			
			{% endfor %}
			</ul>
		</li>
	{% endfor %}
	
	</ul>
	
</div>

{% endblock %}