myschoolcommute/urls.py
from django.conf.urls import url, include, patterns
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()


urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include("massadmin.urls")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Translation app
    url(r'^rosetta/', include('rosetta.urls')),

    #Accounts
    url(r'^accounts/', include('accounts.urls')),

    # district/school list on front-page
    url(r'^$', 'survey.views.index', name='home'),

    # static pages
    url(r'^about/$', TemplateView.as_view(template_name='survey/about.html'), name='about'),
    url(r'^resources/$', TemplateView.as_view(template_name='survey/resources.html'), name='resources'),

    # custom admin pages
    url(r'^districts/$', 'survey.views.district_list', name='district_list'),
    url(r'^(?P<district_slug>[-\w]+)/(?P<school_slug>[-\w]+)/edit/$', 'survey.views.school_edit', name='school_edit'),
    url(r'^(?P<district_slug>[-\w]+)/(?P<school_slug>[-\w]+)/batch/$', 'survey.views.batch_form', name='survey_batch_form'),

    # district
    url(r'^(?P<district_slug>[-\w]+)/$', 'survey.views.district', name='school_list'),
    url(r'^(?P<districtid>[-\w]+)/schools/$', 'survey.views.get_schools', name='disctrict_get_schools'),
    url(r'^(?P<districtid>[-\w]+)/streets/$', 'survey.views.get_streets', name='disctrict_get_streets'),

    # school
    url(r'^(?P<district_slug>[-\w]+)/(?P<school_slug>[-\w]+)/$', 'survey.views.form', name='survey_school_form'),
)

urlpatterns += patterns('',
    # Testing
    url(r'^testr/$', 'survey.views.testr'),

    # Generate report
    url(r'^(?P<school_id>\d+)/(?P<start>\d{4}-\d{2}-\d{2})_(?P<end>\d{4}-\d{2}-\d{2})_report\.pdf$', 'survey.views.school_report', name='school_report'),

    #Typeahead
    url(r'^(?P<school_id>\d+)/streets/(?P<query>[^/]*)/?$', 'survey.views.school_streets'),
    url(r'^(?P<school_id>\d+)/crossing/(?P<street>[^/]+)/(?P<query>[^/]*)/?$', 'survey.views.school_crossing' ),
    url(r'^(?P<school_id>\d+)/intersection/(?P<street1>[^/]+)/(?P<street2>[^/]*)/?$', 'survey.views.intersection' ),

    # admin data
    url(r'^(?P<school_id>\d+)/walkshed.geojson$', 'survey.maps.school_sheds_json', name='sheds_json'),
    url(r'^(?P<school_id>\d+)/surveys.geojson$', 'survey.maps.school_surveys_json', name='surveys_json'),
    url(r'^(?P<school_id>\d+)/walkshed.png$', 'survey.maps.school_sheds', name='school_sheds'),
    url(r'^(?P<school_id>\d+)/walkshed.(?P<format>\w+)$', 'survey.maps.school_sheds', name='school_sheds_format'),
    url(r'^survey_child_survey\.csv$', 'survey.views.surveys_csv', name='surveys_csv'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^walkboston/', include('walkboston.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    # Translation app
    (r'^rosetta/', include('rosetta.urls')),
    
    # district/school list on front-page
    (r'^$', 'survey.views.index'),
    
    # static pages
    (r'^about/$', direct_to_template, {'template': 'survey/about.html'}),
    
    # district
    (r'^(?P<district_slug>[-\w]+)/$', 'survey.views.district'),
    url(r'^(?P<districtid>[-\w]+)/schools/$', 'survey.views.get_schools', name='disctrict_get_schools'),
    url(r'^(?P<districtid>[-\w]+)/streets/$', 'survey.views.get_streets', name='disctrict_get_streets'),
    # school
    url(r'^(?P<district_slug>[-\w]+)/(?P<school_slug>[-\w]+)/$', 'survey.views.form', name='survey_school_form'),    
)

survey/models.py
from django.contrib.gis.db import models
from django.db.models import permalink
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.gis.geos import GEOSGeometry, MultiPolygon, Polygon, GeometryCollection
from django.core.urlresolvers import reverse

# lazy translation
from django.utils.translation import ugettext_lazy as _

# south introspection rules
try:
    from south.modelsinspector import add_introspection_rules
    add_introspection_rules([], ['^django\.contrib\.gis\.db\.models\.fields\.PointField'])
    add_introspection_rules([], ['^django\.contrib\.gis\.db\.models\.fields\.MultiPolygonField'])
    add_introspection_rules([], ['^django\.contrib\.gis\.db\.models\.fields\.MultiLineStringField'])
except ImportError:
    pass

from datetime import datetime, timedelta


class District(models.Model):
    """ School Districts """
    districtid = models.IntegerField(primary_key=True)
    distname = models.CharField(max_length=35)
    slug = models.SlugField(max_length=35, unique=True)
    startgrade = models.CharField(max_length=2)
    endgrade = models.CharField(max_length=2)
    distcode4 = models.CharField(max_length=4)
    distcode8 = models.CharField(max_length=8)

    geometry = models.MultiPolygonField(srid=26986)
    objects = models.GeoManager()

    @property
    def name(self):
        return self.distname

    def __unicode__(self):
        return self.distname

    class Meta:
        ordering = ['distname']


class CustomManager(models.GeoManager):
    def get_query_set(self):
        qs = super(CustomManager, self).get_query_set()
        return qs.defer('shed_05', 'shed_10', 'shed_15', 'shed_20', 'geometry')


class School(models.Model):
    """ School """
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True, null=True)

    schid = models.CharField('School ID', max_length=8, blank=True, null=True, unique=True)
    address = models.CharField(max_length=150, blank=True, null=True)
    town_mail = models.CharField(max_length=25, blank=True, null=True)
    town = models.CharField(max_length=25, blank=True, null=True)
    state = models.CharField(max_length=2, blank=True, null=True)
    zip = models.CharField(max_length=10, blank=True, null=True)
    principal = models.CharField(max_length=50, blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    fax = models.CharField(max_length=15, blank=True, null=True)
    grades = models.CharField(max_length=70, blank=True, null=True)
    schl_type = models.CharField(max_length=3, blank=True, null=True)
    districtid = models.ForeignKey('District', blank=True, null=True)

    survey_incentive = models.TextField(blank=True, null=True)
    # Renamed to disable for now
    _active = models.BooleanField(
        'Is survey active? (Disabled)', db_column='survey_active', default=False
    )

    # GeoDjango
    geometry = models.PointField(srid=26986)
    shed_05 = models.MultiPolygonField(srid=26986, null=True, blank=True)
    shed_10 = models.MultiPolygonField(srid=26986, null=True, blank=True)
    shed_15 = models.MultiPolygonField(srid=26986, null=True, blank=True)
    shed_20 = models.MultiPolygonField(srid=26986, null=True, blank=True)
    objects = CustomManager()


    def __init__(self, *args, **kwargs):
        super(School, self).__init__(*args, **kwargs)
        self.__init__geometry = self.geometry

    def __unicode__(self):
        return self.name

    @property
    def survey_active(self):
        return SurveySet.objects.filter(
            Q(school=self) &
            Q(begin__lte=datetime.now()) &
            Q(end__gte=datetime.now())
        ).count() > 0

    @property
    def district(self):
        return self.districtid

    @permalink
    def get_absolute_url(self):
        return ('survey_school_form', None, {'school_slug': self.slug, 'district_slug': self.districtid.slug})

    def get_intersections(self):
        # school_circle = self.geometry.buffer(5000)
        # intersections = Intersection.objects.filter(geometry__intersects=school_circle)
        relation = SchoolTown.objects.get(schid=self.schid)
        intersections = Intersection.objects.filter(town_id=relation.town_id)
        return intersections

    def update_sheds(self):
        from maps import get_sheds
        sheds = get_sheds(self.id)

        shed_05 = GEOSGeometry(sheds[0.5])
        shed_10 = GEOSGeometry(sheds[1.0])
        shed_15 = GEOSGeometry(sheds[1.5])
        shed_20 = GEOSGeometry(sheds[2.0])

        def coerce_to_multipolygon(geometry):
            if geometry.area == 0:
                return None

            if type(geometry) == MultiPolygon:
                return geometry
            elif type(geometry) == Polygon:
                return MultiPolygon(geometry)
            elif type(geometry) == GeometryCollection:
                polys = []
                for g in geometry:
                    if type(g) == Polygon:
                        polys.append(g)
                    elif type(g) == MultiPolygon:
                        polys += list(g)
                if any(polys):
                    return MultiPolygon(polys)
                else:
                    return None
            else:
                return geometry

        shed_20_ring = shed_20.difference(shed_15)
        self.shed_20 = coerce_to_multipolygon(shed_20_ring)

        shed_15_ring = shed_15.difference(shed_10)
        self.shed_15 = coerce_to_multipolygon(shed_15_ring)

        shed_10_ring = shed_10.difference(shed_05)
        self.shed_10 = coerce_to_multipolygon(shed_10_ring)

        self.shed_05 = coerce_to_multipolygon(shed_05)

    def save(self, *args, **kwargs):
        super(School, self).save(*args, **kwargs)

        SchoolTown.objects.create(schid=self.schid, name=self.name, town_id=self.districtid.districtid)

        # the geometry actually needs to be commited first to be used in update
        if 'commit' not in kwargs or kwargs['commit'] is not False:

            # new school
            if self.__init__geometry is None and self.geometry is not None:
                # new school, generate sheds
                self.update_sheds()
                # save the sheds
                super(School, self).save(*args, **kwargs)

            # school has moved
            elif not self.__init__geometry.equals_exact(self.geometry, 0.001):
                self.update_sheds()
                # save the sheds
                super(School, self).save(*args, **kwargs)

    class Meta:
        ordering = ['name']


class SchoolTown(models.Model):
    ogc_fid = models.AutoField(primary_key=True)
    schid = models.CharField(max_length=8, blank=True, null=True, unique=True)
    name = models.CharField(max_length=200)
    town_id = models.IntegerField(db_column='muni_id')

    class Meta:
        db_table = 'school_muni'


class Street(models.Model):
    """
    Streets to be returned as type-ahead in street-fields
    to limit the variety of street names and make geocoding
    more accurate.
    """
    name = models.CharField(max_length=240)
    districtid = models.ForeignKey('District', blank=True, null=True)

    geometry = models.MultiLineStringField(srid=26986)
    objects = models.GeoManager()

    def __unicode__(self):
        return self.name


class Intersection(models.Model):
    ogc_fid = models.IntegerField(primary_key=True)
    geometry = models.GeometryField(null=True, blank=True, srid=26986)
    st_name_1 = models.CharField(max_length=50, blank=True)
    st_name_2 = models.CharField(max_length=50, blank=True)
    town = models.CharField(max_length=50, blank=True)
    town_id = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True, db_column='long')

    objects = models.GeoManager()

    class Meta:
        db_table = 'survey_intersection'

    def __unicode__(self):
        return "%s - %s" % (self.st_name_1, self.st_name_2, )


class Survey(models.Model):
    """
    Survey base questions.
    """
    school = models.ForeignKey(School)
    street = models.CharField(max_length=50, blank=True, null=True)
    cross_st = models.CharField(
        'Cross street', max_length=50, blank=True, null=True
    )
    nr_vehicles = models.IntegerField(
        'Number of Vehicles', blank=True, null=True
    )
    nr_licenses = models.IntegerField(
        'Number of License', blank=True, null=True
    )
    ip = models.IPAddressField('IP Address', blank=True, null=True)
    # Mile, shortest driving distance, not walk/bike distance
    distance = models.FloatField(null=True)
    created = models.DateTimeField(null=True)
    modified = models.DateTimeField(auto_now=True, null=True)

    user = models.ForeignKey(User, null=True)
    # GeoDjango
    location = models.PointField(
        geography=True, blank=True, null=True, default='POINT(0 0)'
    )
    # default SRS 4326
    objects = models.GeoManager()

    def __unicode__(self):
        return u'%s' % (self.id)

    def update_location(self):
        if len(self.street) > 0 and len(self.cross_st) > 0:
            school_cross = self.school.get_intersections()
            crosses = school_cross.filter(
                Q(
                    Q(st_name_1__iexact=self.street) &
                    Q(st_name_2__iexact=self.cross_st)
                ) |
                Q(
                    Q(st_name_2__iexact=self.street) &
                    Q(st_name_1__iexact=self.cross_st)
                )
            )
            crosses = list(crosses)
            if len(crosses):
                self.location = crosses[0].geometry
                self.location.transform(4326)
            else:
                print 'No Intersection'

    def update_distance(self):
        from maps import get_driving_distance

        try:
            self.distance = get_driving_distance(

survey/templates/survey/about.html
{% extends "base.html" %}
{% load i18n %}

{% block container %}

<div class="span12">
    <h2>{% trans "About the Massachusetts Safe Routes to School Program" %}</h2>

    <p>
        {% trans "The Massachusetts" %} <a href="http://www.commute.com/schools/" title="Safe Routes to School">Safe Routes to School (SRTS)</a> {% trans "program partners with schools throughout the Commonwealth to help plan and implement programs that increase student walking and biking activities.  The program’s goals are to reduce traffic congestion and air pollution near schools while increasing the health, safety, and physical activity of students." %}
    </p>

    <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#about">{% trans "Read more..." %}</button>
    <div id="about" class="collapse">
        <p>
            {% blocktrans %}Evaluating trends in how students and families choose to travel to school is a key component to building a successful Safe Routes to School program. Parent responses to this survey provide valuable information and help determine how we can improve the environment around the school, target investments, track progress toward goals and ultimately develop local programs that benefit students, parents and our communities.{% endblocktrans %}
        </p>
        <p>
            {% blocktrans %}Massachusetts Safe Routes to School is a federally funded initiative of the Massachusetts Department of Transportation (MassDOT).  Over 600 elementary and middle schools, reaching over 270,000 students in 170 communities throughout the Commonwealth participate in the program.  Established in 2006, SRTS encourages elementary and middle school students to walk and bicycle to school safely by implementing the Safe Routes Five E’s: Education, Encouragement, Enforcement, Evaluation and Engineering.{% endblocktrans %}
        </p>
        <p>
            {% trans "Safe Routes to School technical services and program offerings include:" %}
            <ul>
                <li>{% trans "SRTS task force formation" %}</li>
                <li>{% trans "Pedestrian and bicycle safety education and training" %}</li>
                <li>{% trans "SRTS encouragement activities" %}</li>
                <li>{% trans "SRTS gear and incentive items" %}</li>
                <li>{% trans "Infrastructure assessments and improvements" %}</li>
                <li>{% trans "Middle school PhotoVoice workshop series" %}</li>
                <li>{% trans "Walking School Bus toolkit and development" %}</li>
                <li>{% trans "School walking and biking assessments" %}</li>
                <li>{% trans "SRTS program evaluation" %}</li>
                <li>{% trans "Summer program" %}</li>
            </ul>
        </p>
    </div>

    <h3>{% trans "Survey Administration" %}</h3>

    <p>
        {% trans "Safe Routes to School staff will assist partner schools with the administration of this 3-minute, online survey. Informational and marketing materials are available for schools to make parents aware of the online survey tool and provide them with a link to the survey.  Paper versions of the survey are also available and Safe Routes to School program staff can assist with the survey collection process.  Both the online and paper versions are available in multiple languages.  School administrators can have direct access to survey results and reports through an administrative login on the website and program staff can also assist with report generation and the presentation of results." %}
    </p>

    <h3>{% trans "Survey Results" %}</h3>

    <p>{% trans "School and district level reports include a summary of the results accompanied by maps, tables, and charts. The reports are available to school and community officials." %}  {% trans "For more information, please contact MassDOT’s" %}<a href="http://www.commute.com/schools/" title="Safe Routes to School">Safe Routes to School (SRTS)</a> {% trans "program at 857-368-8638." %}</p>

    <h3>{% trans "Survey Development" %}</h3>

    <p>{% trans "The original design and development of the Safe Routes to School survey tool was a collaborative effort of" %} <a href="" title="Metropolitan Area Planning Council">Metropolitan Area Planning Council</a> (MAPC) {% trans "and" %} <a href="http://www.walkboston.org/" title="WalkBoston">WalkBoston</a> {% trans "with support from the" %} <a href="http://www.barrfoundation.org/" title="Barr Foundation">Barr Foundation</a>. {% trans "In 2012, MAPC and WalkBoston published" %} <em>Kids are Commuters Too!</em>, {% trans "a report assessing the walkability of more than 800 schools in Metro Boston and describing the results of surveys received from 4,500 students in seven school districts. To read the report or learn more about the analysis, visit" %} <a href="http://www.mapc.org/srts/" title="MAPC SRTS page">www.mapc.org/srts</a>.</p>

    <h3>{% trans "About MassDOT" %}</h3>

    <p>{% trans "The Massachusetts Department of Transportation (MassDOT) operates the Commonwealth’s Safe Routes to School program with funds from the Federal Highway Division. The Massachusetts Safe Routes to School model of inclusiveness emphasizes a collaborative, community-focused approach that fosters mutual partnerships between advocacy groups, law enforcement, education leaders and public health departments which all work together to promote safer routes for children to get to school." %}</p>

    <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#dot">{% trans "Read more..." %}</button>
    <div id="dot" class="collapse">
        <p>{% trans "The Safe Routes to School program is a key component of the Healthy Transportation Compact and MassDOT’s GreenDOT plan. The Healthy Transportation compact is a ground-breaking collaboration between the departments of transportation, health and human services, and energy and environmental affairs that is designed to promote best practices, increase efficiency, and achieve positive health outcomes through the coordination of land use, transportation and public health policy. GreenDOT calls for MassDOT to incorporate sustainability into all of its activities, from strategic planning to project design and construction to system operation. The GreenDOT policy initiative includes greenhouse gas reduction targets mandated under the Global Warming Solutions Act, signed by Governor Deval Patrick in 2008." %}</p>
    </div>

    <h3>{% trans "About the National Center for Safe Routes to School" %}</h3>

    <p>{% trans "Established in May 2006, the National Center for Safe Routes to School assists states and communities in enabling and encouraging children to safely walk and bicycle to school. The National Center serves as the information clearinghouse for the federal Safe Routes to School program. The organization also provides technical support and resources and coordinates online registration efforts for Walk to School Day and Bike to School Day in the U.S.A. and facilitates worldwide promotion and participation in International Walk to School Day. The National Center is part of the University of North Carolina Highway Safety Research Center with funding from the U.S. Department of Transportation Federal Highway Administration. For more information, visit" %} <a href="http://www.saferoutesinfo.org/" title="Safe Routes Center">www.saferoutesinfo.org</a>.</p>


</div>

{% endblock %}

survey/templates/survey/district.html
{% extends "base.html" %}
{% load i18n %}

{% block container %}

    <h2>{{ district.distname }}</h2>

    <table class='table table-hover'>
        <thead>
            <tr><th>School name</th><th>Number of surveys</th><th>Is Active</th><th>Batch Entry</th></tr>
        </thead>
    {% for school in district.school_set.all %}

        <tr>
            <td><a href="{{ school.slug }}/edit/">{{ school.name }}</a></td>
            <td>{{ school.survey_set.count }}</td>
            <td>{{ school.survey_active }}</td>
            <td><a class='btn btn-small' href="{{ school.slug }}/batch/">Begin Entry</a></td>
        </tr>

    {% endfor %}
    </table>

{% endblock %}

survey/templates/survey/district_list.html
{% extends "base.html" %}
{% load i18n %}

{% block container %}

	<h2>Districts</h2>
	
	<table class='table table-hover'>
		<thead>
			<tr><th>District name</th><th>Number of Schools</th><th>Number of Surveys</th></tr>
		</thead>
	{% for district in districts %}
	
		<tr>
			<td><a href="/{{ district.slug }}/">{{ district.distname }}</a></td>
			<td>{{ district.school_count }}</td>
			<td>{{ district.survey_count }}</td>
		</tr>
	
	{% endfor %}
	</table>

{% endblock %}

survey/templates/survey/school_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block javascript %}
{{block.super}}
<link href="{{ STATIC_URL }}css/datepicker.css" rel="stylesheet">
<script src="{{ STATIC_URL }}js/bootstrap-datepicker.js"></script>

<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css" />
<script src="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js"></script>

<script src="http://maps.google.com/maps/api/js?v=3.2&amp;sensor=false"></script>
<script src="{{ STATIC_URL }}js/Leaflet.Google.js"></script>

<style type='text/css'>
    #map { height: 420px; padding-bottom:1em;}
</style>

<script type="text/javascript">

var color_map = {
    '2.0': "00FFFF",
    '1.5': "#6600CC",
    '1.0': "#9966FF",
    '0.5': "#FF33FF"
};

$(document).ready(function(){
    var school_loc = [{{ school.geometry.y }}, {{ school.geometry.x }}];

    var map = L.map('map').setView(school_loc, 13);

    var mq = L.tileLayer('http://otile{s}.mqcdn.com/tiles/1.0.0/osm/{z}/{x}/{y}.png', {
        maxZoom: 18,
        subdomains: '123',
        attribution: "Imagery Copyright (c) <a href='http://MapQuest.com'>MapQuest</a>"
    });

    var ggl = new L.Google('ROADMAP');
    map.addLayer(ggl);
    map.addControl(new L.Control.Layers( {'MapQuest':mq, 'Google':ggl}, {}));

    var paths, surveys;

    $.getJSON('/{{school.pk}}/walkshed.geojson', function(data){
        paths = L.geoJson(data, {
            style: function(feature) {
                console.log(feature.properties);
                return {
                    color: color_map[feature.properties.distance],
                    weight: 1,
                    opacity: 0.3
                };
            }
        }).addTo(map);
    });

    var circle = L.circle(school_loc, 50, {
        color: 'red',
        fillColor: '#f03',
        fillOpacity: 0.5
    }).addTo(map);

    $('.dateinput').datepicker({ format: "mm/dd/yyyy" });

    $("[rel=tooltip]").tooltip({placement:'top', html:true});;

    {% if request.user.is_staff %}
    var surveys = {
        "type": "FeatureCollection",
        "features": [
            {% for s in school.survey_set.all %}{
                "type": "Feature",
                "geometry": {{s.location.json|safe}},
                "properties": { "id": {{s.pk}}}
            }{% if not forloop.last %},{% endif %}{% endfor %}
        ]
    };
    var geojsonMarkerOptions = {
        radius: 3,
        fillColor: "#ff7800",
        color: "#000",
        weight: 1,
        opacity: 1,
        fillOpacity: 0.8
    };
    var surveys_layer = L.geoJson(surveys, {
        pointToLayer: function (feature, latlng) {
            return L.circleMarker(latlng, geojsonMarkerOptions);
        }
    }).addTo(map)
    {% endif %}
});

</script>
{% endblock %}

{% block container %}
<div class='row-fluid'>
    <div class='span12'>
        <h3>{{district.distname}}, {{school.name}}</h3>
    </div>
</div>
<div class='row-fluid'>
    <div class='span3'>
        <div class='well'>
            <p><h4>Summary <small> - {% now "SHORT_DATE_FORMAT" %}</small></h4></p>

            <p>{{ count_day }} surveys in past 24 hours</p>
            <p>{{ count_week }} surveys in past week</p>
            <p>{{ surveys.count }} surveys in total</p>
            <p>{% if school.survey_active %}
                Survey is <strong>active</strong>
            {% else %}
                Survey is inactive
            {% endif %}
            </p>
        </div>
        <div class='well'>
            <p><h4>Paper Surveys</h4></p>
            <p>For paper survey templates and other resources for a successful survey, visit the <a href='/resources/'>District Resources</a> page</p>
        </div>
    </div>
    <div class='span9'>
        <div id="map"></div>
        <a href='{% url "school_sheds_format" school.pk 'pdf' %}'>Click here for a school walkshed map</a>
    </div>
</div>

<div class='row-fluid'>
    <div class='span9 offset3'>
        <form action="." method="post" class="form-horizontal">
        {{ formset.management_form }}{% csrf_token %}
        {% if formset.forms|length > 1 %}
            <legend>Survey Instances</legend>
            {{ formset.non_form_errors }}
            <table class='table'>
                <thead>
                    <tr>
                        <th>Surveys</th>
                        <th>Status</th>
                        <th>Report</th>
                        <th>Begin</th>
                        <th>End</th>
                    </tr>
                </thead>
                <tbody>
                {% for form in formset %}
                    {% if not forloop.last %}
                    {% with ss=form.instance count=form.instance.surveys_count %}
                        <tr>
                            <td><strong>{{count}}{{form.errors}}</strong></td>
                            <td>
                                {% if ss.begin <= now and ss.end >= now %}
                                In Progress
                                {% else %}
                                Finished
                                {% endif %}
                            <td>
                                {% if count > 1 %}
                                <a target='_blank' href='{{ss.report_url}}'>View</a>
                                {% endif %}
                            </td>
                            <td>
                                {{form.id}}{{ss.begin|date}}
                                <div class='hide'>{{form.begin}}</div>
                            </td>
                            <td>
                                {{ss.end|date}}
                                <div class='hide'>{{form.end}}</div>
                            </td>
                        </tr>
                    {% endwith %}
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
        <legend>New Survey Instance</legend>
        <fieldset>
            {{formset.forms|last|crispy}}
        </fieldset>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
        </form>
    </div>
</div>

{% endblock %}

survey/templates/survey/thanks.html
{% extends "base.html" %}
{% load i18n %}

{% block container %}

	<h2>{% trans "Thank you!" %}</h2>
	<p>Your survey was successfully submitted.</p>

{% endblock %}