accounts/urls.py
from django.conf.urls import url, include, patterns
from django.contrib.auth.models import User
from django.views.generic import ListView
from forms import LoginForm

from views import *

urlpatterns = patterns('',
    url(r'^$', index, name='accounts'),

    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'accounts/logout.html'}, name="logout"),

    url(r'^register/$', register, name='register'),
    url(r'^register/success/$', register_success, name='register_success'),

    url(r'^password/change/$', 'django.contrib.auth.views.password_change', {'template_name': 'accounts/password_change_form.html'}, name='password_change'),
    url(r'^password/done/$', 'django.contrib.auth.views.password_change_done', {'template_name': 'accounts/password_change_done.html'}, name='passwork_change_done'),

    url(r'^reset/$', 'django.contrib.auth.views.password_reset', {'template_name': 'accounts/password_reset_form.html'}, name='password_reset'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_done', {'template_name': 'accounts/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/token/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'template_name': 'accounts/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/complete/$', 'django.contrib.auth.views.password_reset_complete', {'template_name': 'accounts/password_reset_complete.html'}, name='password_reset_complete'),

    (r'^profile/$', profile_authed),
    url(r'^edit/$', profile_edit),
    url(r'^edit/(?P<username>\w+)/$', profile_edit, name='user_edit'),
    url(r'^profile/(?P<username>\w+)/$', profile, name='user_detail'),

    url(r'^users/$',
        ListView.as_view(
            queryset=User.objects.all(),
            context_object_name='object_list',
            template_name='accounts/user_list.html'
        ), name='user_list'
    ),
)

myschoolcommute/urls.py
from django.conf.urls import url, include, patterns
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()


urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include("massadmin.urls")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Translation app
    url(r'^rosetta/', include('rosetta.urls')),

    #Accounts
    url(r'^accounts/', include('accounts.urls')),

    # district/school list on front-page
    url(r'^$', 'survey.views.index', name='home'),

    # static pages
    url(r'^about/$', TemplateView.as_view(template_name='survey/about.html'), name='about'),
    url(r'^resources/$', TemplateView.as_view(template_name='survey/resources.html'), name='resources'),

    # custom admin pages
    url(r'^districts/$', 'survey.views.district_list', name='district_list'),
    url(r'^(?P<district_slug>[-\w]+)/(?P<school_slug>[-\w]+)/edit/$', 'survey.views.school_edit', name='school_edit'),
    url(r'^(?P<district_slug>[-\w]+)/(?P<school_slug>[-\w]+)/batch/$', 'survey.views.batch_form', name='survey_batch_form'),

    # district
    url(r'^(?P<district_slug>[-\w]+)/$', 'survey.views.district', name='school_list'),
    url(r'^(?P<districtid>[-\w]+)/schools/$', 'survey.views.get_schools', name='disctrict_get_schools'),
    url(r'^(?P<districtid>[-\w]+)/streets/$', 'survey.views.get_streets', name='disctrict_get_streets'),

    # school
    url(r'^(?P<district_slug>[-\w]+)/(?P<school_slug>[-\w]+)/$', 'survey.views.form', name='survey_school_form'),
)

urlpatterns += patterns('',
    # Testing
    url(r'^testr/$', 'survey.views.testr'),

    # Generate report
    url(r'^(?P<school_id>\d+)/(?P<start>\d{4}-\d{2}-\d{2})_(?P<end>\d{4}-\d{2}-\d{2})_report\.pdf$', 'survey.views.school_report', name='school_report'),

    #Typeahead
    url(r'^(?P<school_id>\d+)/streets/(?P<query>[^/]*)/?$', 'survey.views.school_streets'),
    url(r'^(?P<school_id>\d+)/crossing/(?P<street>[^/]+)/(?P<query>[^/]*)/?$', 'survey.views.school_crossing' ),
    url(r'^(?P<school_id>\d+)/intersection/(?P<street1>[^/]+)/(?P<street2>[^/]*)/?$', 'survey.views.intersection' ),

    # admin data
    url(r'^(?P<school_id>\d+)/walkshed.geojson$', 'survey.maps.school_sheds_json', name='sheds_json'),
    url(r'^(?P<school_id>\d+)/surveys.geojson$', 'survey.maps.school_surveys_json', name='surveys_json'),
    url(r'^(?P<school_id>\d+)/walkshed.png$', 'survey.maps.school_sheds', name='school_sheds'),
    url(r'^(?P<school_id>\d+)/walkshed.(?P<format>\w+)$', 'survey.maps.school_sheds', name='school_sheds_format'),
    url(r'^survey_child_survey\.csv$', 'survey.views.surveys_csv', name='surveys_csv'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^walkboston/', include('walkboston.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    # Translation app
    (r'^rosetta/', include('rosetta.urls')),
    
    # district/school list on front-page
    (r'^$', 'survey.views.index'),
    
    # static pages
    (r'^about/$', direct_to_template, {'template': 'survey/about.html'}),
    
    # district
    (r'^(?P<district_slug>[-\w]+)/$', 'survey.views.district'),
    url(r'^(?P<districtid>[-\w]+)/schools/$', 'survey.views.get_schools', name='disctrict_get_schools'),
    url(r'^(?P<districtid>[-\w]+)/streets/$', 'survey.views.get_streets', name='disctrict_get_streets'),
    # school
    url(r'^(?P<district_slug>[-\w]+)/(?P<school_slug>[-\w]+)/$', 'survey.views.form', name='survey_school_form'),    
)

accounts/models.py
from django.contrib.gis.db import models
from django.contrib.auth.models import User

from survey.models import District, School


class Profile(models.Model):
    user = models.ForeignKey(User, unique=True, verbose_name='user')
    telephone = models.CharField(max_length=20, null=True, blank=False)
    official_title = models.CharField(max_length=50, null=True, blank=False)
    district = models.ForeignKey(District, null=True, blank=False)
    school = models.ForeignKey(School, null=True, blank=True)

    def get_all_fields(self):
        """Returns a list of all field names on the instance."""
        fields = []
        for f in self._meta.fields:

            fname = f.name
            # resolve picklists/choices, with get_xyz_display() function
            get_choice = 'get_'+fname+'_display'
            if hasattr(self, get_choice):
                value = getattr(self, get_choice)()
            else:
                try:
                    value = getattr(self, fname)
                except User.DoesNotExist:
                    value = None

            # only display fields with values and skip some fields entirely
            if f.editable and value and f.name not in ('id','user',):
                fields.append({
                    'label': f.verbose_name,
                    'name': f.name,
                    'value': value,
                })

        return fields

    def __unicode__(self):
        return self.user.username


def user_post_save(sender, instance, **kwargs):
    profile, new = Profile.objects.get_or_create(user=instance)

models.signals.post_save.connect(user_post_save, User)

accounts/forms.py
from django.contrib.auth.models import User, Group
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.gis import admin
from django.template.loader import render_to_string
from django.utils.safestring import mark_safe
from django.contrib.auth.forms import AuthenticationForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout, Fieldset, ButtonHolder, Submit

from models import Profile
from survey.models import District, School

class InitModelForm(forms.ModelForm):
    """
    Subclass of `forms.ModelForm` that makes sure the initial values
    are present in the form data, so you don't have to send all old values
    for the form to actually validate.
    """
    def merge_from_initial(self):
        filt = lambda v: v not in self.data.keys()
        for field in filter(filt, getattr(self.Meta, 'fields', ())):
            self.data[field] = self.initial.get(field, None)

# I put this on all required fields, because it's easier to pick up
# on them with CSS or JavaScript if they have a class of "required"
# in the HTML. Your mileage may vary. If/when Django ticket #3515
# lands in trunk, this will no longer be necessary.
attrs_dict = {'class': 'required', 'style': 'font-weight: bold;'}


class LoginForm(AuthenticationForm, forms.Form):
    class Meta:
        layout = (
            Fieldset("Please Login", "username", "password", ),
        )

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.add_input(Submit('submit', 'Log in'))


class RegistrationForm(forms.Form):
    """
    Form for registering a new user account.

    Validates that the requested username is not already in use, and
    requires the password to be entered twice to catch typos.

    Subclasses should feel free to add any additional validation they
    need, but should avoid defining a ``save()`` method -- the actual
    saving of collected user data is delegated to the active
    registration backend.

    """
    username = forms.RegexField(regex=r'^\w+$',
                                max_length=30,
                                widget=forms.TextInput(attrs=attrs_dict),
                                label=_("Username"),
                                error_messages={ 'invalid': _("This value must contain only letters, numbers and underscores.") })

    password1 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
                                label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
                                label=_("Password (again)"))

    first_name = forms.CharField(max_length=30, label=_("First name"), required=True)
    last_name = forms.CharField(max_length=30, label=_("Last name"), required=True)

    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               maxlength=75)),
                             label=_("Email address"))

    group = forms.ModelChoiceField(
        queryset=Group.objects.all(), help_text="Which admin group are you in?"
        #Hide group selection, comment out below to re-enable
        , initial= Group.objects.get(name="District Officials")
        , widget= forms.HiddenInput()
    )

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.form_tag = False
        #self.helper.add_input(Submit('submit', 'Create the account'))

    def clean_username(self):
        """
        Validate that the username is alphanumeric and is not already
        in use.

        """
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("A user with that username already exists."))

    def clean_email(self):
        """
        Validate that the supplied email address is unique for the
        site.
        """

        if User.objects.filter(email__iexact=self.cleaned_data['email']).count():
            raise forms.ValidationError(_(u'This email address is already in use. Please supply a different email address.'))
        return self.cleaned_data['email']

    def clean(self):
        """
        Verifiy that the values entered into the two password fields
        match. Note that an error here will end up in
        ``non_field_errors()`` because it doesn't apply to a single
        field.

        """
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields didn't match."))
        return self.cleaned_data

    def save(self, commit=True):
        u = User.objects.create_user(username=self.cleaned_data['username'],
                                     email=self.cleaned_data['email'],
                                     password=self.cleaned_data['password1'])
        u.first_name = self.cleaned_data['first_name']
        u.last_name = self.cleaned_data['last_name']
        u.is_active = False

        group = self.cleaned_data['group']

        if commit:
            u.save()
            u.groups.add(group)
        else:
            old_save_m2m = u.save_m2m
            def save_m2m():
                old_save_m2m()
                u.groups.add(group)
            u.save_m2m = save_m2m
        return u


class UserForm(InitModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.CharField(required=True)

    def __init__(self, *args, **kwargs):
        editor = kwargs.pop('editor', None)
        super(UserForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.form_tag = False

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', )


class ProfileForm(InitModelForm):
    school = forms.ModelChoiceField(
        required=False,
        queryset=School.objects.all().defer('shed_05', 'shed_10', 'shed_15', 'shed_20')
    )
    def __init__(self, *args, **kwargs):
        editor = kwargs.pop('editor', None)
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.form_tag = False
        if editor:
            if not editor.is_superuser or editor.groups.filter(name="MassRIDES Staff").count() == 0:
                self.fields['district'].widget.attrs['readonly'] = 'readonly'

    class Meta:
        model = Profile
        exclude = ('user',)

accounts/templates/accounts/edit.html
{% extends "accounts/index.html" %}
{% load crispy_forms_tags %}
{% block title %}Edit Account {{block.super}}{% endblock %}

{% block head_extra %}
{{ block.super }}
{{ profile_form.media }}
{% endblock%}

{% block content %}
    <legend>Edit Account</legend>
    <br/>
    <form class="form-horizontal" method="post" action=".">
        {% csrf_token %}
        {% if request.user.username != user.username and perms.accounts.change_profile %}
        <div class="control-group">
            <label class="control-label" for="is_active"><b>Is Active</b></label>
            <div class="controls">
                <label class="checkbox">
                    <input type="checkbox" id="is_active" name='is_active' {% if user.is_active %}checked="checked"{% endif %} >
                    Check here if user information looks good and 'Save the account'.
                </label>
            </div>
        </div>
        {% endif %}
        {% crispy user_form %}
        {% crispy profile_form %}
    </form>
{% endblock %}

accounts/templates/accounts/index.html
{# This template holds the things that appear on all account pages #}
{% extends 'base.html' %}

{% block container %}
<div class='row-fluid'>
    <div class='span3'>
        <div class='well sidebar-nav'>
            <ul class="nav nav-list">
                <li class="nav-header">Account</li>
                {{text}}
                {% if user.is_authenticated %}
                {% if request.path == "/inputs/" %}class="active"{% endif %}
                <li {% if "/accounts/users/" in request.path %}class="active"{% endif %}>
                    <a href='/accounts/users/'><i class="icon-th-list"></i> View Users</a>
                </li>
                <li {% if "/accounts/profile/" in request.path %}class="active"{% endif %}>
                    <a href="/accounts/profile/{{request.user.username}}/"><i class="icon-user"></i> View Profile</a>
                </li>
                <li {% if "/accounts/edit/" in request.path %}class="active"{% endif %}>
                    <a href='/accounts/edit/'><i class="icon-pencil"></i> Edit Profile</a>
                </li>
                <li {% if "/accounts/password/" in request.path %}class="active"{% endif %}>
                    <a href='/accounts/password/change/'><i class="icon-pencil"></i> Change Password</a>
                </li>
                <li {% if "/accounts/logout/" in request.path %}class="active"{% endif %}>
                    <a href="/accounts/logout/"><i class="icon-off"></i> Log out</a>
                </li>
                {% else %}
                <li {% if "/accounts/login/" in request.path %}class="active"{% endif %}>
                    <a href='/accounts/login/'>Log In</a>
                </li>
                <li {% if "/accounts/register/" in request.path %}class="active"{% endif %}>
                    <a href='/accounts/register/'>Register</a>
                </li>
                <li {% if "/accounts/reset/" in request.path %}class="active"{% endif %}>
                    <a href='/accounts/reset/'>Reset Password</a>
                </li>
                {% endif %}
                {% if user.is_staff %}
                <li class="nav-header">Staff Actions</li>
           		<li><a href="/admin/">Administer</a></li>
           		{% endif %}
            </ul>    
        </div>
    </div>
    <div class='span9'>
        {% block content %}{{content}}{% endblock %}
    </div>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/index.html' %}
{% block title %}Log in {{block.super}}{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<legend>Log in</legend>
{% crispy form %}
{% endblock %}

accounts/templates/accounts/logout.html
{% extends "accounts/index.html" %}
{% load i18n %}

{% block content %}
<h3>{% trans "Logged out" %}</h3>
{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends "accounts/index.html" %}
{% load i18n %}

{% block title %}{% trans 'Password change successful' %} {{block.super}}{% endblock %}

{% block content %}

<h2>{% trans 'Password change successful' %}</h2>

<p>{% trans 'Your password was changed.' %}</p>

{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends "accounts/index.html" %}
{% load i18n %}

{% block title %}{% trans 'Password change' %} {{block.super}}{% endblock %}

{% block content %}

<h2>{% trans 'Password change' %}</h2>

<p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

<form action="" method="post">
{% csrf_token %}
{{ form.old_password.errors }}
<p class="aligned wide"><label for="id_old_password">{% trans 'Old password:' %}</label>{{ form.old_password }}</p>
{{ form.new_password1.errors }}
<p class="aligned wide"><label for="id_new_password1">{% trans 'New password:' %}</label>{{ form.new_password1 }}</p>
{{ form.new_password2.errors }}
<p class="aligned wide"><label for="id_new_password2">{% trans 'Confirm password:' %}</label>{{ form.new_password2 }}</p>

<p><input type="submit" class='btn btn-primary' value="{% trans 'Change my password' %}" /></p>
</form>

{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "accounts/index.html" %}
{% load i18n %}

{% block breadcrumbs %}<div class="breadcrumbs"><a href="../../">{% trans 'Home' %}</a> &rsaquo; {% trans 'Password reset' %}</div>{% endblock %}

{% block title %}{% trans 'Password reset complete' %} {{block.super}}{% endblock %}

{% block content %}

<h2>{% trans 'Password reset complete' %}</h2>

<p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{{ login_url }}">{% trans 'Log in' %}</a></p>

{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "accounts/index.html" %}
{% load i18n %}

{% block breadcrumbs %}<div class="breadcrumbs"><a href="../">{% trans 'Home' %}</a> &rsaquo; {% trans 'Password reset confirmation' %}</div>{% endblock %}

{% block title %}{% trans 'Password reset' %} {{block.super}}{% endblock %}

{% block content %}

{% if validlink %}

<label>{% trans 'Enter new password' %}</label>

<p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

<form action="" method="post">
{% csrf_token %}
{{ form.new_password1.errors }}
<p class="aligned wide"><label for="id_new_password1">{% trans 'New password:' %}</label>{{ form.new_password1 }}</p>
{{ form.new_password2.errors }}
<p class="aligned wide"><label for="id_new_password2">{% trans 'Confirm password:' %}</label>{{ form.new_password2 }}</p>
<p><input type="submit" value="{% trans 'Change my password' %}" class='btn' /></p>
</form>

{% else %}

<h1>{% trans 'Password reset unsuccessful' %}</h1>

<p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}

{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "accounts/index.html" %}
{% load i18n %}

{% block breadcrumbs %}<div class="breadcrumbs"><a href="../">{% trans 'Home' %}</a> &rsaquo; {% trans 'Password reset' %}</div>{% endblock %}

{% block title %}{% trans 'Password reset successful' %}{% endblock %}

{% block content %}

<h2>{% trans 'Password reset successful' %}</h2>

<p>{% trans "We've e-mailed you instructions for setting your password to the e-mail address you submitted. You should be receiving it shortly." %}</p>

{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% trans "You're receiving this e-mail because you requested a password reset" %}
{% blocktrans %}for your user account at {{ site_name }}{% endblocktrans %}.

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url "django.contrib.auth.views.password_reset_confirm" uidb36=uid, token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/accounts/password_reset_form.html
{% extends "accounts/index.html" %}
{% load i18n %}

{% block breadcrumbs %}<div class="breadcrumbs"><a href="../">{% trans 'Home' %}</a> &rsaquo; {% trans 'Password reset' %}</div>{% endblock %}

{% block title %}{% trans "Password reset" %}{% endblock %}

{% block content %}

<legend>{% trans "Password reset" %}</legend>

<p>{% trans "Forgotten your password? Enter your e-mail address below, and we'll e-mail instructions for setting a new one." %}</p>

<form action="" method="post">
{% csrf_token %}
{{ form.email.errors }}
<p><label for="id_email">{% trans 'E-mail address:' %}</label> {{ form.email }} <br/><input type="submit" value="{% trans 'Reset my password' %}" class='btn' /></p>
</form>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends "accounts/index.html" %}

{% block title %}{{username}} - {% endblock %}

{% block content %}
      <h2>{{username}}</h2>
      <br/>
<dl class="dl-horizontal">
{% for f in user_f %}
	{% if f.data %}
    <dt>{{ f.label|capfirst }}</dt> <dd>{{f.data}}</dd>
    {% endif %}
{% endfor %}

{% for f in profile.get_all_fields %}
    <dt>{{ f.label|capfirst }}{% if f.label %} {%endif%}</dt>
    <dd>{{ f.value }}</dd>
{% endfor %}

</dl>
{% endblock %}

accounts/templates/accounts/register_success.html
{% extends 'accounts/index.html' %}

{% block content %}
<legend>Registeration Success</legend>
<p>Your registration has been filed.</p>
<p>Please wait for an administrator to review your registration and activate your account.</p>
<p>Once your account is active, you will be able to log-in.</p>
{% endblock %}

accounts/templates/accounts/user_list.html
{% extends 'accounts/index.html' %}
{% block title %}Users {{block.super}}{% endblock %}
{% block content %}
<h2>Users</h2>
<br/>
<table class="table table-striped">
	<thead>
		<tr>
            {% if perms.accounts.change_profile %}
            <th><b>Is activated</b></th>
            {% endif %}
            <th><b>Username</b></th> <th><b>Name<b></th> <th><b>Last login<b></th>
        </tr>
	</thead>
{% for o in object_list %}
<tr>
    {% if perms.accounts.change_profile %}
    <td><b>{{o.is_active}}</b></td>
    {% endif %}
    <td>
        {% if perms.accounts.change_profile %}
        <a href='{% url "user_edit" o.username %}'><i class="icon-pencil"></i></a>
        {% endif %}
        <strong><a href="{% url "user_detail" o.username %}">{{o.username}}</a></strong>

    </td>
    <td>{{o.first_name}} {{o.last_name}}</td>
    <td>{{o.last_login|date:"jS F Y H:i"}}</td>
</tr>
{% endfor %}
</table>
{% endblock %}