myschoolcommute/urls.py
from django.conf.urls import url, include, patterns
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()


urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include("massadmin.urls")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Translation app
    url(r'^rosetta/', include('rosetta.urls')),

    #Accounts
    url(r'^accounts/', include('accounts.urls')),

    # district/school list on front-page
    url(r'^$', 'survey.views.index', name='home'),

    # static pages
    url(r'^about/$', TemplateView.as_view(template_name='survey/about.html'), name='about'),
    url(r'^resources/$', TemplateView.as_view(template_name='survey/resources.html'), name='resources'),

    # custom admin pages
    url(r'^districts/$', 'survey.views.district_list', name='district_list'),
    url(r'^(?P<district_slug>[-\w]+)/(?P<school_slug>[-\w]+)/edit/$', 'survey.views.school_edit', name='school_edit'),
    url(r'^(?P<district_slug>[-\w]+)/(?P<school_slug>[-\w]+)/batch/$', 'survey.views.batch_form', name='survey_batch_form'),

    # district
    url(r'^(?P<district_slug>[-\w]+)/$', 'survey.views.district', name='school_list'),
    url(r'^(?P<districtid>[-\w]+)/schools/$', 'survey.views.get_schools', name='disctrict_get_schools'),
    url(r'^(?P<districtid>[-\w]+)/streets/$', 'survey.views.get_streets', name='disctrict_get_streets'),

    # school
    url(r'^(?P<district_slug>[-\w]+)/(?P<school_slug>[-\w]+)/$', 'survey.views.form', name='survey_school_form'),
)

urlpatterns += patterns('',
    # Testing
    url(r'^testr/$', 'survey.views.testr'),

    # Generate report
    url(r'^(?P<school_id>\d+)/(?P<start>\d{4}-\d{2}-\d{2})_(?P<end>\d{4}-\d{2}-\d{2})_report\.pdf$', 'survey.views.school_report', name='school_report'),

    #Typeahead
    url(r'^(?P<school_id>\d+)/streets/(?P<query>[^/]*)/?$', 'survey.views.school_streets'),
    url(r'^(?P<school_id>\d+)/crossing/(?P<street>[^/]+)/(?P<query>[^/]*)/?$', 'survey.views.school_crossing' ),
    url(r'^(?P<school_id>\d+)/intersection/(?P<street1>[^/]+)/(?P<street2>[^/]*)/?$', 'survey.views.intersection' ),

    # admin data
    url(r'^(?P<school_id>\d+)/walkshed.geojson$', 'survey.maps.school_sheds_json', name='sheds_json'),
    url(r'^(?P<school_id>\d+)/surveys.geojson$', 'survey.maps.school_surveys_json', name='surveys_json'),
    url(r'^(?P<school_id>\d+)/walkshed.png$', 'survey.maps.school_sheds', name='school_sheds'),
    url(r'^(?P<school_id>\d+)/walkshed.(?P<format>\w+)$', 'survey.maps.school_sheds', name='school_sheds_format'),
    url(r'^survey_child_survey\.csv$', 'survey.views.surveys_csv', name='surveys_csv'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^walkboston/', include('walkboston.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    # Translation app
    (r'^rosetta/', include('rosetta.urls')),
    
    # district/school list on front-page
    (r'^$', 'survey.views.index'),
    
    # static pages
    (r'^about/$', direct_to_template, {'template': 'survey/about.html'}),
    
    # district
    (r'^(?P<district_slug>[-\w]+)/$', 'survey.views.district'),
    url(r'^(?P<districtid>[-\w]+)/schools/$', 'survey.views.get_schools', name='disctrict_get_schools'),
    url(r'^(?P<districtid>[-\w]+)/streets/$', 'survey.views.get_streets', name='disctrict_get_streets'),
    # school
    url(r'^(?P<district_slug>[-\w]+)/(?P<school_slug>[-\w]+)/$', 'survey.views.form', name='survey_school_form'),    
)

survey/models.py
from django.contrib.gis.db import models
from django.db.models import permalink
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.gis.geos import GEOSGeometry, MultiPolygon, Polygon, GeometryCollection
from django.core.urlresolvers import reverse

# lazy translation
from django.utils.translation import ugettext_lazy as _

# south introspection rules
try:
    from south.modelsinspector import add_introspection_rules
    add_introspection_rules([], ['^django\.contrib\.gis\.db\.models\.fields\.PointField'])
    add_introspection_rules([], ['^django\.contrib\.gis\.db\.models\.fields\.MultiPolygonField'])
    add_introspection_rules([], ['^django\.contrib\.gis\.db\.models\.fields\.MultiLineStringField'])
except ImportError:
    pass

from datetime import datetime, timedelta


class District(models.Model):
    """ School Districts """
    districtid = models.IntegerField(primary_key=True)
    distname = models.CharField(max_length=35)
    slug = models.SlugField(max_length=35, unique=True)
    startgrade = models.CharField(max_length=2)
    endgrade = models.CharField(max_length=2)
    distcode4 = models.CharField(max_length=4)
    distcode8 = models.CharField(max_length=8)

    geometry = models.MultiPolygonField(srid=26986)
    objects = models.GeoManager()

    @property
    def name(self):
        return self.distname

    def __unicode__(self):
        return self.distname

    class Meta:
        ordering = ['distname']


class CustomManager(models.GeoManager):
    def get_query_set(self):
        qs = super(CustomManager, self).get_query_set()
        return qs.defer('shed_05', 'shed_10', 'shed_15', 'shed_20', 'geometry')


class School(models.Model):
    """ School """
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True, null=True)

    schid = models.CharField('School ID', max_length=8, blank=True, null=True, unique=True)
    address = models.CharField(max_length=150, blank=True, null=True)
    town_mail = models.CharField(max_length=25, blank=True, null=True)
    town = models.CharField(max_length=25, blank=True, null=True)
    state = models.CharField(max_length=2, blank=True, null=True)
    zip = models.CharField(max_length=10, blank=True, null=True)
    principal = models.CharField(max_length=50, blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    fax = models.CharField(max_length=15, blank=True, null=True)
    grades = models.CharField(max_length=70, blank=True, null=True)
    schl_type = models.CharField(max_length=3, blank=True, null=True)
    districtid = models.ForeignKey('District', blank=True, null=True)

    survey_incentive = models.TextField(blank=True, null=True)
    # Renamed to disable for now
    _active = models.BooleanField(
        'Is survey active? (Disabled)', db_column='survey_active', default=False
    )

    # GeoDjango
    geometry = models.PointField(srid=26986)
    shed_05 = models.MultiPolygonField(srid=26986, null=True, blank=True)
    shed_10 = models.MultiPolygonField(srid=26986, null=True, blank=True)
    shed_15 = models.MultiPolygonField(srid=26986, null=True, blank=True)
    shed_20 = models.MultiPolygonField(srid=26986, null=True, blank=True)
    objects = CustomManager()


    def __init__(self, *args, **kwargs):
        super(School, self).__init__(*args, **kwargs)
        self.__init__geometry = self.geometry

    def __unicode__(self):
        return self.name

    @property
    def survey_active(self):
        return SurveySet.objects.filter(
            Q(school=self) &
            Q(begin__lte=datetime.now()) &
            Q(end__gte=datetime.now())
        ).count() > 0

    @property
    def district(self):
        return self.districtid

    @permalink
    def get_absolute_url(self):
        return ('survey_school_form', None, {'school_slug': self.slug, 'district_slug': self.districtid.slug})

    def get_intersections(self):
        # school_circle = self.geometry.buffer(5000)
        # intersections = Intersection.objects.filter(geometry__intersects=school_circle)
        relation = SchoolTown.objects.get(schid=self.schid)
        intersections = Intersection.objects.filter(town_id=relation.town_id)
        return intersections

    def update_sheds(self):
        from maps import get_sheds
        sheds = get_sheds(self.id)

        shed_05 = GEOSGeometry(sheds[0.5])
        shed_10 = GEOSGeometry(sheds[1.0])
        shed_15 = GEOSGeometry(sheds[1.5])
        shed_20 = GEOSGeometry(sheds[2.0])

        def coerce_to_multipolygon(geometry):
            if geometry.area == 0:
                return None

            if type(geometry) == MultiPolygon:
                return geometry
            elif type(geometry) == Polygon:
                return MultiPolygon(geometry)
            elif type(geometry) == GeometryCollection:
                polys = []
                for g in geometry:
                    if type(g) == Polygon:
                        polys.append(g)
                    elif type(g) == MultiPolygon:
                        polys += list(g)
                if any(polys):
                    return MultiPolygon(polys)
                else:
                    return None
            else:
                return geometry

        shed_20_ring = shed_20.difference(shed_15)
        self.shed_20 = coerce_to_multipolygon(shed_20_ring)

        shed_15_ring = shed_15.difference(shed_10)
        self.shed_15 = coerce_to_multipolygon(shed_15_ring)

        shed_10_ring = shed_10.difference(shed_05)
        self.shed_10 = coerce_to_multipolygon(shed_10_ring)

        self.shed_05 = coerce_to_multipolygon(shed_05)

    def save(self, *args, **kwargs):
        super(School, self).save(*args, **kwargs)

        SchoolTown.objects.create(schid=self.schid, name=self.name, town_id=self.districtid.districtid)

        # the geometry actually needs to be commited first to be used in update
        if 'commit' not in kwargs or kwargs['commit'] is not False:

            # new school
            if self.__init__geometry is None and self.geometry is not None:
                # new school, generate sheds
                self.update_sheds()
                # save the sheds
                super(School, self).save(*args, **kwargs)

            # school has moved
            elif not self.__init__geometry.equals_exact(self.geometry, 0.001):
                self.update_sheds()
                # save the sheds
                super(School, self).save(*args, **kwargs)

    class Meta:
        ordering = ['name']


class SchoolTown(models.Model):
    ogc_fid = models.AutoField(primary_key=True)
    schid = models.CharField(max_length=8, blank=True, null=True, unique=True)
    name = models.CharField(max_length=200)
    town_id = models.IntegerField(db_column='muni_id')

    class Meta:
        db_table = 'school_muni'


class Street(models.Model):
    """
    Streets to be returned as type-ahead in street-fields
    to limit the variety of street names and make geocoding
    more accurate.
    """
    name = models.CharField(max_length=240)
    districtid = models.ForeignKey('District', blank=True, null=True)

    geometry = models.MultiLineStringField(srid=26986)
    objects = models.GeoManager()

    def __unicode__(self):
        return self.name


class Intersection(models.Model):
    ogc_fid = models.IntegerField(primary_key=True)
    geometry = models.GeometryField(null=True, blank=True, srid=26986)
    st_name_1 = models.CharField(max_length=50, blank=True)
    st_name_2 = models.CharField(max_length=50, blank=True)
    town = models.CharField(max_length=50, blank=True)
    town_id = models.IntegerField(null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True, db_column='long')

    objects = models.GeoManager()

    class Meta:
        db_table = 'survey_intersection'

    def __unicode__(self):
        return "%s - %s" % (self.st_name_1, self.st_name_2, )


class Survey(models.Model):
    """
    Survey base questions.
    """
    school = models.ForeignKey(School)
    street = models.CharField(max_length=50, blank=True, null=True)
    cross_st = models.CharField(
        'Cross street', max_length=50, blank=True, null=True
    )
    nr_vehicles = models.IntegerField(
        'Number of Vehicles', blank=True, null=True
    )
    nr_licenses = models.IntegerField(
        'Number of License', blank=True, null=True
    )
    ip = models.IPAddressField('IP Address', blank=True, null=True)
    # Mile, shortest driving distance, not walk/bike distance
    distance = models.FloatField(null=True)
    created = models.DateTimeField(null=True)
    modified = models.DateTimeField(auto_now=True, null=True)

    user = models.ForeignKey(User, null=True)
    # GeoDjango
    location = models.PointField(
        geography=True, blank=True, null=True, default='POINT(0 0)'
    )
    # default SRS 4326
    objects = models.GeoManager()

    def __unicode__(self):
        return u'%s' % (self.id)

    def update_location(self):
        if len(self.street) > 0 and len(self.cross_st) > 0:
            school_cross = self.school.get_intersections()
            crosses = school_cross.filter(
                Q(
                    Q(st_name_1__iexact=self.street) &
                    Q(st_name_2__iexact=self.cross_st)
                ) |
                Q(
                    Q(st_name_2__iexact=self.street) &
                    Q(st_name_1__iexact=self.cross_st)
                )
            )
            crosses = list(crosses)
            if len(crosses):
                self.location = crosses[0].geometry
                self.location.transform(4326)
            else:
                print 'No Intersection'

    def update_distance(self):
        from maps import get_driving_distance

        try:
            self.distance = get_driving_distance(

survey/templates/base.html
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}School Commute Survey</title>
    <meta name="description" content="WalkBoston To School Parent Survey">
    <meta name="keywords" content="Boston, Metro, Planning, Education, Survey, Pedestrian, Walking">
    <meta name="author" content="MAPC">

    <!-- geotags -->
    <meta name="DC.title" content="to school">
    <meta name="geo.placename" content="Boston">
    <meta name="geo.position" content="42.34;-71.08">
    <meta name="geo.region" content="US-MA">
    <meta name="ICBM" content="42.34;-71.08">

    <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css">
    <style type="text/css">
      .sidebar-nav {
        padding: 9px 0;
      }
      .asteriskField {
          display: none;
      }
      .requiredField {
          font-weight: bold;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
        body {
          padding-top: 0;
        }
      }
      body {
        padding-top: 55px;
      }
      .footer-row {
        height: 100px;
      }
      .footer-span {
        position: relative;
        height: 100%;
      }
      .footer-span img{
        position: absolute;
        bottom: 0;
        max-height: 70px;
      }
      .errorlist {
        color: #D8000C;
      }
    </style>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-responsive.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">

    <style type="text/css">
    {% block style %}{% endblock %}
    </style>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js" type="text/javascript"></script>

    {% block javascript %}{% endblock %}

    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-5547782-11']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top too-high" id="base-body-div-area">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="{% url 'home' %}">MASafeRoutesSurvey.org</a>
          {% if request.user.is_authenticated %}
          {% with profile=request.user.get_profile %}
          <div class="nav-collapse collapse">
            <ul class="nav">
                <li {% if 'accounts' in request.path %}class='active'{% endif %}><a href="/accounts/">Accounts</a></li>
                <li {% if 'resources' in request.path %}class='active'{% endif %}><a href="/resources/">District Resources</a></li>
                {% if perms.survey.change_district %}
                <li><a href="{% url 'district_list' %}">Districts</a></li>
                {% endif %}
                <li {% if request.path|slice:"4:-1" == profile.district.slug %}class='active'{% endif %}>
                  <a href="{% url 'school_list' profile.district.slug %}">{{profile.district}} Schools</a>
                </li>
                {% if profile.school %}
                <li {% if profile.school.slug in request.path %}class='active'{% endif %}>
                  <a href="{% url 'school_edit' profile.school.districtid.slug profile.school.slug %}">
                  {{profile.school.name}}
                  </a>
                </li>
                {% endif %}
            </ul>
          </div>
          {% endwith %}
          {% endif %}
          <div class="nav-collapse collapse">
            <ul class="nav">
                <li><a href="{% url 'about' %}">{% trans "About" %}</a></li>
                {% for lang_code, lang_name in LANGUAGES %}
                    <li {% ifequal lang_code LANGUAGE_CODE %}class="active"{% endifequal %}>
                      {% language lang_code %}
                        <a href="{% url 'home' %}">{% trans lang_name %}</a>
                      {% endlanguage %}
                    </li>
                {% endfor %}
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="main container {{ LANGUAGE_CODE }}">
        <div class="row">
            <div class="span12 ">
                {% block container %}{% endblock %}
            </div>
        </div>
    </div>

    <hr>
    <footer>
      {% trans "Questions?" %} <a href="mailto:admin@masaferoutessurvey.org?subject=MASafeRoutesSurvey.org%20Website%20Question">{% trans "Please click here to email us." %}</a><br />
      {% if request.user.is_authenticated %}
        <a href='{% url 'accounts' %}'>Administration Account</a>
        {% if request.user.is_staff %}
        <br><a href='{% url 'surveys_csv' %}'>Download Surveys CSV</a>
        {% endif %}
      {% else %}
        Are you an administrator? <a href='/accounts/login/'>Log in</a> or <a href='/accounts/register/'>Register</a>
      {% endif %}<br/>
            &copy; <a href="http://www.mapc.org" title="Metropolitan Area Planning Council">MAPC</a> 2011
    </footer>

</body>
</html>